feat: 받은 피드백 카드 UI 구현
depromeet/na-lab-client pull request #109
Opened 2023-05-20 15:49 UTC by oyeon-kwon

## 🎉 변경 사항
받은 피드백 카드 UI 입니다. 3D로 이미지 변경되고 나면 머지할게요!

### 🙏 여기는 꼭 봐주세요!
- CollaborationBadge 컴포넌트를 색상에 따라 2가지로 사용 가능하게 바꾸었어요! (`Default는 파란 배경`, `Gray는 회색 배경`)

## 🌄 스크린샷
<img width="757" alt="스크린샷 2023-05-21 오전 12 13 53" src="https://github.com/depromeet/na-lab-client/assets/61301574/35b50514-64cc-424f-b666-edeab6efa3db">

2023-05-20 19:14 UTC, sumi-0011 commented on src/features/feedback/ReceivedFeedbackCard.tsx
> +      <header css={FeedbackHeader}>{isRead ? null : <UnreadBadgeIcon />}</header>
`header` 태그 안에는 하나 이상의 제목이 있어야 한다고 알고있었는데, 
이 부분에는 아이콘 밖에 없는 것 같아서 header 의 역할 보단, 단순히 카드의 상단 역할 만을 하는 것 같아요!
이런 경우에는 `header`, `footer`을 사용하지 않고, `div`와 같은 태그를 사용하는건 어떨까요? 

> 모두의 생각이 궁금합니다!  @oyeon-kwon @hyesungoh @sjoleee

2023-05-21 01:38 UTC, sjoleee requested changes
<img width="195" alt="image" src="https://github.com/depromeet/na-lab-client/assets/82137004/dd2206b2-d18d-432a-87fb-3811e9d422fb">

디자인이랑 간격, 높이같은것들이 미묘하게 어긋난부분이 조금씩 보여요 ㅠㅠ
한번 다시 점검해주시면 좋을것같아유!

<img width="117" alt="image" src="https://github.com/depromeet/na-lab-client/assets/82137004/58801c83-d3f2-46b8-9433-46fd59a09a1c">

뱃지는 flex, alignitem center, box-sizing borderbox 필요할듯합니다!

2023-05-21 01:38 UTC, sjoleee requested changes
<img width="195" alt="image" src="https://github.com/depromeet/na-lab-client/assets/82137004/dd2206b2-d18d-432a-87fb-3811e9d422fb">

디자인이랑 간격, 높이같은것들이 미묘하게 어긋난부분이 조금씩 보여요 ㅠㅠ
한번 다시 점검해주시면 좋을것같아유!

<img width="117" alt="image" src="https://github.com/depromeet/na-lab-client/assets/82137004/58801c83-d3f2-46b8-9433-46fd59a09a1c">

뱃지는 flex, alignitem center, box-sizing borderbox 필요할듯합니다!

2023-05-21 01:41 UTC, sjoleee commented on src/features/feedback/ReceivedFeedbackCard.tsx
> +      <header css={FeedbackHeader}>{isRead ? null : <UnreadBadgeIcon />}</header>
저는 시멘틱하게 개발하는편은 아니라 잘 모르긴 하지만.. 디자인이나 기능 측면이 아니고 접근성만을 위해서 래핑하는게 괜찮은가 싶긴 합니다..?

2023-05-21 07:01 UTC, hyesungoh commented on src/features/feedback/ReceivedFeedbackCard.tsx
> +      <header css={FeedbackHeader}>{isRead ? null : <UnreadBadgeIcon />}</header>
헤더 안에 헤딩이 있는 것을 권장하긴 하네요!
https://developer.mozilla.org/ko/docs/Web/HTML/Element/header#%EC%82%AC%EC%9A%A9_%EC%9D%BC%EB%9E%8C

저는 한 페이지에 한 개의 헤더와 푸터를 사용하는 것을 좋아하곤 하는데, 효과가 있는지, SEO 관점에서 유리한 지는 잘 모르겠어요.

이런 경우에는 article, section, div 정도가 제 취향이긴해요~

2023-05-22 16:42 UTC, oyeon-kwon commented on src/features/feedback/ReceivedFeedbackCard.tsx
> +      <header css={FeedbackHeader}>{isRead ? null : <UnreadBadgeIcon />}</header>
오호.. 좋은 의견들 감사합니다
내부에 아이콘밖에 없어서 article 보다는 div가 더 적당한 느낌이네요..!

2023-05-22 16:42 UTC, oyeon-kwon commented on src/features/feedback/ReceivedFeedbackCard.tsx
> +  left: 0;
앗 피그마 css 복붙..입니도

2023-05-23 06:56 UTC, oyeon-kwon commented on src/features/feedback/ReceivedFeedbackCard.tsx
> +      <header css={FeedbackHeader}>{isRead ? null : <UnreadBadgeIcon />}</header>
아 아이콘을 앱솔루트로 줘서 div 태그 없애겠습니다~!

2023-05-23 07:01 UTC, oyeon-kwon commented on src/features/feedback/ReceivedFeedbackCard.tsx
> +  width: 161px;
min-width 설정해서 요렇게 해놓을게요!
<img width="177" alt="스크린샷 2023-05-23 오후 4 00 58" src="https://github.com/depromeet/na-lab-client/assets/61301574/80418979-c392-4b48-be21-f7dc322c4204">

2023-05-23 07:03 UTC, oyeon-kwon commented on src/features/feedback/ReceivedFeedbackCard.tsx
> +`;
넵!!!

2023-05-23 07:03 UTC, oyeon-kwon commented on src/features/feedback/ReceivedFeedbackCard.tsx
> +  left: 0;
삭제완~

2023-05-23 07:34 UTC, oyeon-kwon commented on src/features/feedback/ReceivedFeedbackCard.tsx
> +  padding: 10px 10px 30px;
감사합니당 고쳤습니다!

2023-05-26 04:15 UTC, merged