쌓인 연구일지 보러가기 버튼
depromeet/na-lab-client pull request #141
Opened 2023-05-23 14:47 UTC by oyeon-kwon

## 🙏 여기는 꼭 봐주세요!
- 추후 3D 이미지 적용 시 반영 예정입니다!

## 🌄 스크린샷
<img width="427" alt="스크린샷 2023-05-23 오후 11 46 00" src="https://github.com/depromeet/na-lab-client/assets/61301574/4feacb67-d8cb-4f9b-a235-3ead43a1eea5">

2023-05-23 15:02 UTC, sumi-0011 requested changes
시멘틱 태그를 어떻게 사용하는지 같이 찾아봐야 할 것 같아요! 헷갈리네요 ㅎㅎ
button 안에 section, article이 있기엔 button이 작은 단위인것 같아요. 
대체로 레이아웃에서 section, article을 사용하는 것으로 알고있어요!

2023-05-23 15:02 UTC, sumi-0011 commented on src/features/feedback/ResearchMoveButton.tsx
> +import files from '../../../public/images/files.png';
이미지가 public 폴더에 있다면,
`/images/files.png` 로 접근 가능합니다!

2023-05-23 16:54 UTC, hyesungoh commented on src/components/icons/ChevronArrowRightIcon.tsx
요 아이콘 `ChevronArrowIcon` 정도로 이름을 바꾸고,

https://github.com/depromeet/na-lab-client/blob/53b516b9ffd95324feef15f01bd6702743753ad4/src/components/icons/ArrowIcon.tsx#L4-L30

방향을 설정할 수 있게 하면 어떨까요 ?? 

물론 ~~ 지금 중요하진 않으니 무시해주셔도 좋아요 !!!

2023-05-23 16:56 UTC, oyeon-kwon commented on src/components/icons/ChevronArrowRightIcon.tsx
오호 좋아요! 우선 아이콘 목록에는 오른쪽 방향 밖에 없어서 이렇게 해 두긴 했는데 왼쪽 방향 아이콘도 생기면 말씀하신대로 추가해볼게요 ㅎㅎ 감사합니다!!

2023-05-31 03:16 UTC, oyeon-kwon commented on src/features/feedback/ResearchMoveButton.tsx
> +          <div css={TextWrapperCss(theme)}>
넵! 변경했습니다 ㅎㅎ

2023-05-31 03:41 UTC, merged