Next Auth 카카오 로그인
depromeet/na-lab-client pull request #63
Opened 2023-05-12 08:10 UTC by oyeon-kwon

## 🤔 해결하려는 문제가 무엇인가요?
close #44 

## 🎉 변경 사항
* next-auth를 활용해 카카오 로그인 버튼을 만들었어요.

### 🙏 여기는 꼭 봐주세요!
* 테스트 코드가 올바르게 짠게 맞는지 모르겠네요..

### 사용 방법
* env 파일 추가가 필요합니다. 
👉 [env 노션 문서](https://www.notion.so/depromeet/env-48c5b045bd68494a9d0597e9ee054836)

## 🌄 스크린샷
<img width="524" alt="스크린샷 2023-05-12 오전 12 59 35" src="https://github.com/depromeet/na-lab-client/assets/61301574/d4ab0df9-e598-491a-a65c-b75dae5cb3c8">
<img width="486" alt="스크린샷 2023-05-12 오전 12 59 43" src="https://github.com/depromeet/na-lab-client/assets/61301574/dfc0a5e9-d763-40da-942c-3da218c05c75">

## 📚 참고
* 상조님이 에러 해결 도와주심🙏🏻🙏🏻 감사합니동

2023-05-12 08:32 UTC, hyesungoh commented
넵 캐시 파일 올라오는 거 맞아요!

2023-05-12 08:43 UTC, hyesungoh requested changes
👍 👍 고생하셨습니다!!

`pageExtensions` 설정이랑 pages 하위 routes들 파일명만 원복해주시면 좋을 거 같아요 !

2023-05-12 08:45 UTC, hyesungoh commented on src/components/kakaoLoginButton/KakaoLogin.test.tsx
> +afterEach(cleanup);
`describe` 안에 `beforeEach` 아래에 위치하는게 자연스러울 거 같은데 어떻게 생각하시나요?!

2023-05-12 09:23 UTC, oyeon-kwon commented on src/pages/api/auth/[...nextauth].ts
오..!!! 해보겠습니다!

2023-05-12 09:50 UTC, oyeon-kwon commented on src/components/kakaoLoginButton/KakaoLogin.test.tsx
> +afterEach(cleanup);
앗 저게 언제 저기로 내려갔지..! 감사합니다!!

2023-05-12 09:50 UTC, oyeon-kwon commented on src/pages/api/auth/[...nextauth].ts
흐엉 안되네욥..ㅠ

2023-05-13 06:43 UTC, hyesungoh approved these changes

2023-05-13 07:52 UTC, sjoleee approved these changes
LGTM~

2023-05-13 07:52 UTC, sjoleee commented on next.config.js
> +  pageExtensions: ['page.tsx', 'page.ts'],
👍

2023-05-13 07:52 UTC, sjoleee commented on src/pages/api/auth/[...nextauth].page.ts
> +      clientSecret: process.env.KAKAO_CLIENT_SECRET,
NEXT_PUBLIC 프리픽스 없어도 작동하나유?!

2023-05-13 11:52 UTC, oyeon-kwon commented on src/pages/api/auth/[...nextauth].page.ts
> +      clientSecret: process.env.KAKAO_CLIENT_SECRET,
네넹 되긴하던데 깔끔하게 붙여서 다시 올렸어유~

2023-05-13 14:18 UTC, hyesungoh commented
@oyeon-kwon 요거 배포 환경에서 안되는 것 해결하고 머지하면 좋을 거 같아요 !

> 그리고 에러일 시 보여질 페이지도 ... 있어야될 거 같긴 합니다 ㅋㅋㅋ ㅠㅠ

2023-05-14 02:28 UTC, oyeon-kwon commented
[공식문서](https://next-auth.js.org/deployment)에 보면 vercel이나 netlify도 마찬가지로 랜덤url 생성되는 미리보기 배포가 있는데, 그래서 NEXTAUTH_URL을 안써도 된다고 나오더라구요!

근데 cloudflare에 대한 정보는 없길래 next-auth 레포에 질문 올려놨습니당 
👉 https://github.com/nextauthjs/next-auth/issues/7542

답변 오면 조치해볼게요!!

2023-05-14 05:20 UTC, hyesungoh commented
> [공식문서](https://next-auth.js.org/deployment)에 보면 vercel이나 netlify도 마찬가지로 랜덤url 생성되는 미리보기 배포가 있는데, 그래서 NEXTAUTH_URL을 안써도 된다고 나오더라구요!
> 
> 근데 cloudflare에 대한 정보는 없길래 next-auth 레포에 질문 올려놨습니당 👉 [nextauthjs/next-auth#7542](https://github.com/nextauthjs/next-auth/issues/7542)
> 
> 답변 오면 조치해볼게요!!

https://next-auth.js.org/deployment#example

뭔가 이 예제처럼 preview 환경일 때 ... 를 따로 핸들링해줘야하나도 싶네요 🤔

2023-05-14 08:32 UTC, oyeon-kwon commented
> 뭔가 이 [예제](https://next-auth.js.org/deployment#example)처럼 preview 환경일 때 ... 를 따로 핸들링해줘야하나도 싶네요 🤔

실패... 주르륵

2023-05-20 06:31 UTC, merged