feat: icon 추가
depromeet/na-lab-client pull request #88
Opened 2023-05-18 13:01 UTC by oyeon-kwon

## 🎉 변경 사항
아이콘을 추가했어요.

### 사용 방법
`yarn run sb` 명령어 입력 후 localhost:6006 에서 스토리북으로 확인할 수 있습니다.

2023-05-18 16:01 UTC, sjoleee requested changes
Svg 컴포넌트가 svg태그로 만들어진거라 path만 작성해주는게 어떨까유?!

2023-05-20 05:54 UTC, oyeon-kwon commented
감사합니다! 수정했습니다~!

2023-05-20 08:38 UTC, hyesungoh approved these changes
👍 👍 이름 잘못 들어간 것만 수정 부탁드릴게요! 고생하셨어용 👍 👍

2023-05-20 08:38 UTC, hyesungoh commented on src/components/icons/LineThreeDotsIcon.tsx
> +const XIcon = ({ color = '#3D4350', ...rest }: ComponentProps<typeof Svg>) => {
여기 이름이 잘못들어가있어요 `LineThreeDotsIcon` ㅋㅋㅋㅋㅋ 제가 처음 만들때 이렇게 해버렸어요 죄송함다 ㅋㅋㅋ

2023-05-20 18:34 UTC, oyeon-kwon commented on src/components/icons/LineThreeDotsIcon.tsx
> +const XIcon = ({ color = '#3D4350', ...rest }: ComponentProps<typeof Svg>) => {
아 바꿔야하는게 이거였군요!! 제가 놓쳤네요 ㅋㅋㅋ 감삼당

2023-05-20 18:48 UTC, merged